### If model does not fit then we have to perform the step
- Algo Understanding
- Features Engg
- Sample Size

In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("Dataset/classification/fruits.csv")
df

diameter  weight FruitName
0        3.0      30    Banana
1        6.0     100     Apple
2        6.1      95     Apple
3        3.2      35    Banana
4        5.5      80     Apple
5        7.1     120    Banana
6        2.5      60    Banana
7        2.3     100    Banana
8        4.8      70     Apple
9        4.8      79     Apple
10       5.8     120     Apple
11       2.6      85    Banana
12       6.0     110     Apple
13       6.3      95     Apple
14       3.0      40    Banana
15       3.5      25    Banana
16       5.5     100     Apple
17       7.5     120     Apple
18       2.5      50    Banana
19       2.7      40    Banana
20       4.8      90     Apple
21       5.8      90     Apple

In [3]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
model = KNeighborsClassifier()
model.fit(X,y)

KNeighborsClassifier()

In [4]:
model.predict([[3.5,70]]) # high pirorty of weight(range)

array(['Apple'], dtype=object)

### Feature Scaling(Similar)
- Making all feature in same range
- so that all feature will contibute equally in predicition


#### Note: if we do not perform scaling then a feature with big values will impact the prediction.


#### Technique:
- MinMaxScaler
- MaxAbSacler
- StandardScalar
- Binarizer
- etc.


In [5]:
import numpy as np
X = np.array([[2,20],[1,18],[2,15],[4,50],[3,30],[4,60]])
print(X)

[[ 2 20]
 [ 1 18]
 [ 2 15]
 [ 4 50]
 [ 3 30]
 [ 4 60]]


In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test = train_test_split(X,random_state=1)
X_train

array([[ 3, 30],
       [ 2, 20],
       [ 4, 50],
       [ 4, 60]])

In [7]:
X_test

array([[ 2, 15],
       [ 1, 18]])

In [8]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
sc = MinMaxScaler(feature_range=(0,1))
sc.fit(X_train) # Find (learn) values of xmin,xmax for all features
X_train_new = sc.transform(X_train) # apply actual formula

In [10]:
X_train_new

array([[0.5 , 0.25],
       [0.  , 0.  ],
       [1.  , 0.75],
       [1.  , 1.  ]])

In [11]:
X_test_new = sc.transform(X_test)
X_test_new

array([[ 0.   , -0.125],
       [-0.5  , -0.05 ]])

In [12]:
sc = MinMaxScaler(feature_range=(0,1))
sc.fit_transform(X_train) # Find (learn) values of xmin,xmax as well as apply actual formula
sc.transform(X_test)

array([[ 0.   , -0.125],
       [-0.5  , -0.05 ]])